# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleCli < Formula
  desc "Example CLI application"
  homepage "https://github.com/spinguard/example-cli"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/spinguard/example-cli/releases/download/v1.0.0/example-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "927388cf8ddcb76bf03df1d2b765d2654b6992342c7441eed3c3ead576cc0ce0"

      def install
        bin.install "example-cli"
      end
    end
    on_arm do
      url "https://github.com/spinguard/example-cli/releases/download/v1.0.0/example-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "9978203d68d2eca07eadb74aa1e56380c1258aa06d727384339a587f5e07175c"

      def install
        bin.install "example-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spinguard/example-cli/releases/download/v1.0.0/example-cli_1.0.0_linux_amd64.tar.gz"
        sha256 "c8fb540f854ddeb6daa4d9c494e304f9be8b61855cfea5c08e649b11bd826d2f"

        def install
          bin.install "example-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spinguard/example-cli/releases/download/v1.0.0/example-cli_1.0.0_linux_arm64.tar.gz"
        sha256 "904308f431e47cd5de7744911197a56b9e7787a9656b7c464a0fe950ec25d3ab"

        def install
          bin.install "example-cli"
        end
      end
    end
  end

  test do
    assert_match "example-cli version #{version}", shell_output("#{bin}/example-cli version")
  end
end
