# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleCli < Formula
  desc "Example CLI application"
  homepage "https://github.com/spinguard/example-cli"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/spinguard/example-cli/releases/download/v1.0.2/example-cli_1.0.2_darwin_amd64.tar.gz"
      sha256 "c07d23ceffd39858208617925da8bad7e4de473b4a6e67955e7df1adf285c712"

      def install
        bin.install "example-cli"
      end
    end
    on_arm do
      url "https://github.com/spinguard/example-cli/releases/download/v1.0.2/example-cli_1.0.2_darwin_arm64.tar.gz"
      sha256 "e2c1be8984b74fb3f3783f2f563705708791ac5cd32d800fa8d1a3c50e4cc790"

      def install
        bin.install "example-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spinguard/example-cli/releases/download/v1.0.2/example-cli_1.0.2_linux_amd64.tar.gz"
        sha256 "c795c79760c7b2c4e9bb63d7673999611fcf653ce81ea4c95ebc20a0bfdf9160"

        def install
          bin.install "example-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spinguard/example-cli/releases/download/v1.0.2/example-cli_1.0.2_linux_arm64.tar.gz"
        sha256 "350ed634c5220eb983d33a9b2b2a14e6e1d66b52fd0f90247d74632298d7dbc9"

        def install
          bin.install "example-cli"
        end
      end
    end
  end

  test do
    assert_match "example-cli version #{version}", shell_output("#{bin}/example-cli version")
  end
end
