# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleCli < Formula
  desc "Example CLI application"
  homepage "https://github.com/spinguard/example-cli"
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/spinguard/example-cli/releases/download/v1.0.3/example-cli_1.0.3_darwin_amd64.tar.gz"
      sha256 "e3a29c450d9eeab41fe717b95fab8f9bd663055f66560ee311bc49344e1c8069"

      def install
        bin.install "example-cli"
      end
    end
    on_arm do
      url "https://github.com/spinguard/example-cli/releases/download/v1.0.3/example-cli_1.0.3_darwin_arm64.tar.gz"
      sha256 "a9690948db9726993e71671ea25c2e64608c0dcabe8f718b43618ae9f02a3283"

      def install
        bin.install "example-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spinguard/example-cli/releases/download/v1.0.3/example-cli_1.0.3_linux_amd64.tar.gz"
        sha256 "8ce7a305d3820af72862279effc9bd4eac716c6dd604804d14454cb465d8c05a"

        def install
          bin.install "example-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/spinguard/example-cli/releases/download/v1.0.3/example-cli_1.0.3_linux_arm64.tar.gz"
        sha256 "651305f42e017f2743d1ec0aa03ffccbea10fece4746d589b31663b3701d5929"

        def install
          bin.install "example-cli"
        end
      end
    end
  end

  test do
    assert_match "example-cli version #{version}", shell_output("#{bin}/example-cli version")
  end
end
